#!/usr/bin/env python3
"""Graphify: turn this codebase into a navigable graph of Obsidian notes.

Parses every first-party Python module with the stdlib `ast` module (no third
party deps, no network, nothing installed) and emits:

  <vault>/02 Codebase/Modules/<dotted.name>.md   one note per module, with its
                                                 internal imports as [[wikilinks]]
                                                 so Obsidian's Graph View renders
                                                 the real import graph
  <vault>/07 Graphs/Import Dependency Graph.md   Mermaid graphs (full + core)
  <vault>/07 Graphs/codebase_graph.json          raw nodes/edges for reuse

Usage:
    python3 tools/graphify_codebase.py [--repo yolov3_test] [--vault Versal_YOLOv3_Vault]
"""

import argparse
import ast
import json
import os
from collections import defaultdict

# Directories that are vendored, generated, or virtualenv noise.
EXCLUDE_PARTS = {"__pycache__", ".venv", "site", ".git"}

# Peripheral subtrees - kept in the full graph, dropped from the "core" graph so
# the core view shows the train/val/export/DPU path without logger clutter.
PERIPHERAL_PREFIXES = (
    "utils.loggers",
    "utils.segment",
    "utils.aws",
    "utils.flask_rest_api",
    "utils.triton",
    "models.tf",
)

GENERATED_NOTE = {
    "quantize_result.YOLOv3DPUWrapper": "Generated by the Vitis AI quantizer.",
    "vitis_out.probe_init": "Throwaway debug probe from the segfault hunt.",
}


def discover(repo_root):
    """Returns {dotted_module_name: relative_path} for every first-party .py file."""
    modules = {}
    for dirpath, dirnames, filenames in os.walk(repo_root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_PARTS]
        for fn in filenames:
            if not fn.endswith(".py"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, repo_root)
            parts = rel[:-3].split(os.sep)  # strip .py
            if parts[-1] == "__init__":
                parts = parts[:-1]  # package __init__ IS the package
            if not parts:
                continue
            modules[".".join(parts)] = rel
    return modules


def package_of(dotted, path):
    """The package a module lives in, for resolving relative imports."""
    if os.path.basename(path) == "__init__.py":
        return dotted  # __init__ resolves relative imports against itself
    return dotted.rpartition(".")[0]


def resolve(target, internal):
    """Maps a dotted import to the longest matching internal module, else None."""
    parts = target.split(".")
    for cut in range(len(parts), 0, -1):
        candidate = ".".join(parts[:cut])
        if candidate in internal:
            return candidate
    return None


def analyze(path, dotted, internal, pkg):
    """Extracts imports, classes, functions and LOC from one module via AST."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            src = fh.read()
    except OSError as exc:
        return {"error": str(exc)}

    info = {
        "loc": src.count("\n") + 1,
        "doc": "",
        "classes": [],
        "functions": [],
        "internal_imports": set(),
        "external_imports": set(),
        "error": None,
    }

    try:
        tree = ast.parse(src)
    except SyntaxError as exc:
        info["error"] = "SyntaxError: %s" % exc
        return info

    doc = ast.get_docstring(tree)
    if doc:
        info["doc"] = doc.strip().split("\n")[0][:200]

    for node in tree.body:  # top-level only, keeps the note readable
        if isinstance(node, ast.ClassDef):
            bases = []
            for b in node.bases:
                try:
                    bases.append(ast.unparse(b))
                except Exception:
                    bases.append("?")
            info["classes"].append({"name": node.name, "bases": bases})
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            info["functions"].append(node.name)

    for node in ast.walk(tree):
        targets = []
        if isinstance(node, ast.Import):
            targets = [a.name for a in node.names]
        elif isinstance(node, ast.ImportFrom):
            if node.level:  # relative import: climb from the current package
                base = pkg.split(".") if pkg else []
                climb = base[: len(base) - (node.level - 1)] if node.level > 1 else base
                targets = [".".join(filter(None, climb + [node.module or ""]))]
            else:
                targets = [node.module or ""]
        for t in targets:
            if not t:
                continue
            hit = resolve(t, internal)
            if hit and hit != dotted:
                info["internal_imports"].add(hit)
            elif not hit:
                info["external_imports"].add(t.split(".")[0])

    info["internal_imports"] = sorted(info["internal_imports"])
    info["external_imports"] = sorted(info["external_imports"])
    return info


def mermaid_id(dotted):
    """Mermaid node ids cannot contain dots."""
    return dotted.replace(".", "_").replace("-", "_")


def build_mermaid(nodes, edges, title, skip_peripheral=False):
    """Renders a Mermaid flowchart for the given nodes/edges."""
    keep = set(nodes)
    if skip_peripheral:
        keep = {
            n for n in keep
            if not any(n == p or n.startswith(p + ".") for p in PERIPHERAL_PREFIXES)
        }
    lines = ["```mermaid", "graph LR"]
    groups = defaultdict(list)
    for n in sorted(keep):
        groups[n.split(".")[0] if "." in n else "(root)"].append(n)
    for group, members in sorted(groups.items()):
        lines.append('  subgraph %s["%s"]' % (mermaid_id(group), group))
        for n in members:
            lines.append('    %s["%s"]' % (mermaid_id(n), n))
        lines.append("  end")
    seen = set()
    for src, dst in sorted(edges):
        if src in keep and dst in keep and (src, dst) not in seen:
            seen.add((src, dst))
            lines.append("  %s --> %s" % (mermaid_id(src), mermaid_id(dst)))
    lines.append("```")
    return "\n".join(lines)


def write_module_notes(out_dir, data, importers):
    """One note per module, internal imports rendered as wikilinks."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for dotted, info in sorted(data.items()):
        lines = [
            "---",
            "tags: [code, module]",
            "module: %s" % dotted,
            "path: %s" % info["path"],
            "loc: %d" % info.get("loc", 0),
            "---",
            "",
            "# `%s`" % dotted,
            "",
            "> [!info] Source",
            "> `yolov3_test/%s` - %d lines" % (info["path"], info.get("loc", 0)),
        ]
        if dotted in GENERATED_NOTE:
            lines += ["", "> [!warning] %s" % GENERATED_NOTE[dotted]]
        if info.get("doc"):
            lines += ["", "**Purpose:** %s" % info["doc"]]
        if info.get("error"):
            lines += ["", "> [!bug] Parse issue: %s" % info["error"]]

        deps = info.get("internal_imports", [])
        lines += ["", "## Imports (internal)", ""]
        lines += ["- [[%s]]" % d for d in deps] if deps else ["_None - leaf module._"]

        used_by = sorted(importers.get(dotted, []))
        lines += ["", "## Imported by", ""]
        lines += ["- [[%s]]" % u for u in used_by] if used_by else ["_Nothing imports this (entry point or unused)._"]

        ext = info.get("external_imports", [])
        if ext:
            lines += ["", "## Third-party / stdlib", "", ", ".join("`%s`" % e for e in ext)]

        classes = info.get("classes", [])
        if classes:
            lines += ["", "## Classes", ""]
            for c in classes:
                base = "(%s)" % ", ".join(c["bases"]) if c["bases"] else ""
                lines.append("- `%s%s`" % (c["name"], base))

        funcs = info.get("functions", [])
        if funcs:
            lines += ["", "## Top-level functions", ""]
            lines.append(", ".join("`%s()`" % f for f in funcs))

        if deps or used_by:
            local_edges = [(dotted, d) for d in deps] + [(u, dotted) for u in used_by]
            local_nodes = {dotted, *deps, *used_by}
            lines += ["", "## Local neighbourhood", "",
                      build_mermaid(local_nodes, local_edges, dotted)]

        lines += ["", "---", "", "Back to [[Code Map]] | [[Home]]", ""]

        safe = dotted.replace("/", "-")
        dest = os.path.join(out_dir, "%s.md" % safe)
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
        written.append(dest)
    return written


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--repo", default=os.path.join(here, "yolov3_test"))
    ap.add_argument("--vault", default=os.path.join(here, "Versal_YOLOv3_Vault"))
    opt = ap.parse_args()

    modules = discover(opt.repo)
    internal = set(modules)
    print("[graphify] %d first-party modules found" % len(modules))

    data, edges = {}, []
    importers = defaultdict(set)
    for dotted, rel in modules.items():
        full = os.path.join(opt.repo, rel)
        info = analyze(full, dotted, internal, package_of(dotted, rel))
        info["path"] = rel
        data[dotted] = info
        for dep in info.get("internal_imports", []):
            edges.append((dotted, dep))
            importers[dep].add(dotted)

    notes = write_module_notes(os.path.join(opt.vault, "02 Codebase", "Modules"), data, importers)
    print("[graphify] wrote %d module notes" % len(notes))

    graphs_dir = os.path.join(opt.vault, "07 Graphs")
    os.makedirs(graphs_dir, exist_ok=True)

    orphans = sorted(m for m in modules if not importers.get(m) and not data[m].get("internal_imports"))
    hottest = sorted(importers.items(), key=lambda kv: -len(kv[1]))[:12]

    doc = [
        "---", "tags: [graph, codebase]", "---", "",
        "# Import Dependency Graph", "",
        "Generated by `tools/graphify_codebase.py` (stdlib `ast`; nothing installed).",
        "%d modules, %d internal import edges." % (len(modules), len(set(edges))), "",
        "> [!tip] Obsidian Graph View",
        "> Every module also has its own note under `02 Codebase/Modules/` with its",
        "> imports as wikilinks, so the built-in **Graph View** renders this same",
        "> structure interactively - open it and filter with `path:\"02 Codebase/Modules\"`.",
        "",
        "## Most depended-upon modules", "",
        "| Module | Imported by |", "| --- | --- |",
    ]
    doc += ["| [[%s]] | %d |" % (m, len(imps)) for m, imps in hottest]
    doc += [
        "", "## Core graph", "",
        "_Peripheral subtrees (loggers, segment, aws, flask, triton, tf) omitted._", "",
        build_mermaid(set(modules), edges, "core", skip_peripheral=True),
        "", "## Full graph", "",
        build_mermaid(set(modules), edges, "full"),
    ]
    if orphans:
        doc += ["", "## Standalone modules", "",
                "No first-party imports either way - scripts or shims:", ""]
        doc += ["- [[%s]]" % o for o in orphans]
    doc += ["", "---", "", "Back to [[Code Map]] | [[Home]]", ""]

    with open(os.path.join(graphs_dir, "Import Dependency Graph.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(doc))

    payload = {
        "modules": {
            k: {kk: (sorted(vv) if isinstance(vv, set) else vv) for kk, vv in v.items()}
            for k, v in data.items()
        },
        "edges": sorted(set(edges)),
    }
    with open(os.path.join(graphs_dir, "codebase_graph.json"), "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)

    print("[graphify] graph notes written to %s" % graphs_dir)


if __name__ == "__main__":
    main()
